name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          cd web && npm install && npm run build
      - name: moving files
        run: chmod +x moveweb.sh  && bash moveweb.sh
      - name: print
        run: ls